// Generated by scripts/build-client.mjs. Do not edit by hand.

window.__ModuleLoader__.load({
  id: 'dsh-session-permissions',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    var name = 'dsh-session-permissions'
    var inject = ['slots', 'locale']

const POLICY_SCHEMA_VERSION = 1
const INIT_PRESET = 'research'

const AGENT_PRESET_IDS = ['research', 'developer', 'reviewer', 'release', 'public']
const PRESET_IDS = ['full', 'research', 'developer', 'reviewer', 'release', 'public']
const TOOL_IDS = ['read', 'write', 'edit', 'apply_patch', 'bash', 'deploy']
const READ_IDS = ['none', 'workspace', 'all']
const WRITE_IDS = ['none', 'workspace', 'all']
const SHELL_IDS = ['deny', 'allowlist', 'allow']
const APPROVAL_IDS = ['never', 'ask-external', 'ask-always']
const MCP_IDS = ['none', 'explicit', 'init-defaults']

const PRESETS = {
  full: {
    files: { read: 'all', write: 'all' },
    shell: 'allow',
    tools: { allow: ['read', 'write', 'edit', 'apply_patch', 'bash', 'deploy'], deny: [] },
    delegation: { maxDepth: 8, roles: ['research', 'reviewer', 'developer', 'release', 'public'] },
    approval: 'never',
    mcp: 'init-defaults',
  },
  research: {
    files: { read: 'workspace', write: 'none' },
    shell: 'deny',
    tools: { allow: ['read'], deny: ['write', 'edit', 'apply_patch', 'bash'] },
    delegation: { maxDepth: 1, roles: [] },
    approval: 'never',
    mcp: 'init-defaults',
  },
  developer: {
    files: { read: 'workspace', write: 'workspace' },
    shell: 'allowlist',
    tools: { allow: ['read', 'write', 'edit', 'apply_patch', 'bash'], deny: ['deploy'] },
    delegation: { maxDepth: 1, roles: ['research', 'reviewer'] },
    approval: 'ask-external',
    mcp: 'init-defaults',
  },
  reviewer: {
    files: { read: 'workspace', write: 'none' },
    shell: 'deny',
    tools: { allow: ['read'], deny: ['write', 'edit', 'apply_patch', 'bash', 'deploy'] },
    delegation: { maxDepth: 1, roles: [] },
    approval: 'never',
    mcp: 'init-defaults',
  },
  release: {
    files: { read: 'workspace', write: 'none' },
    shell: 'deny',
    tools: { allow: ['read'], deny: ['write', 'edit', 'apply_patch', 'bash'] },
    delegation: { maxDepth: 1, roles: [] },
    approval: 'ask-always',
    mcp: 'explicit',
  },
  public: {
    files: { read: 'none', write: 'none' },
    shell: 'deny',
    tools: { allow: [], deny: ['read', 'write', 'edit', 'apply_patch', 'bash'] },
    delegation: { maxDepth: 0, roles: [] },
    approval: 'never',
    mcp: 'none',
  },
}

function isPresetId(id) {
  return PRESET_IDS.includes(id)
}

function declaredOf(preset) {
  const id = isPresetId(preset) ? preset : INIT_PRESET
  return { preset: id, enforced: false, ...PRESETS[id] }
}

function pick(list, value, fallback) {
  return list.includes(value) ? value : fallback
}

function asStringList(value) {
  if (!Array.isArray(value)) return []
  return value.filter((item) => typeof item === 'string' && item)
}

function normalizePolicy(raw, fallbackPreset) {
  const value = raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {}
  const preset = isPresetId(value.preset) ? value.preset : (isPresetId(fallbackPreset) ? fallbackPreset : INIT_PRESET)
  const base = declaredOf(preset)
  const filesIn = value.files && typeof value.files === 'object' ? value.files : {}
  const toolsIn = value.tools && typeof value.tools === 'object' ? value.tools : {}
  const delegationIn = value.delegation && typeof value.delegation === 'object' ? value.delegation : {}
  const depth = Number(delegationIn.maxDepth)
  const roles = asStringList(delegationIn.roles)
  return {
    preset,
    enforced: false,
    files: {
      read: pick(READ_IDS, filesIn.read, base.files.read),
      write: pick(WRITE_IDS, filesIn.write, base.files.write),
    },
    shell: pick(SHELL_IDS, value.shell, base.shell),
    tools: {
      allow: Array.isArray(toolsIn.allow) ? asStringList(toolsIn.allow) : base.tools.allow.slice(),
      deny: Array.isArray(toolsIn.deny) ? asStringList(toolsIn.deny) : base.tools.deny.slice(),
    },
    delegation: {
      maxDepth: Number.isFinite(depth) && depth >= 0 ? Math.min(8, Math.floor(depth)) : base.delegation.maxDepth,
      roles: roles.length ? roles : (base.delegation.roles || []).slice(),
    },
    approval: pick(APPROVAL_IDS, value.approval, base.approval),
    mcp: pick(MCP_IDS, value.mcp, base.mcp),
    skills: {
      deny: asStringList(value.skills && value.skills.deny),
    },
  }
}

function applyPreset(preset) {
  return normalizePolicy({ preset }, preset)
}

function isToolEnabled(policy, toolId) {
  const allow = (policy && policy.tools && policy.tools.allow) || []
  const deny = (policy && policy.tools && policy.tools.deny) || []
  if (deny.includes(toolId)) return false
  return allow.includes(toolId)
}

function toggleTool(policy, toolId, enabled) {
  const next = normalizePolicy(policy)
  const allow = new Set(next.tools.allow)
  const deny = new Set(next.tools.deny)
  if (enabled) {
    allow.add(toolId)
    deny.delete(toolId)
  } else {
    allow.delete(toolId)
    deny.add(toolId)
  }
  next.tools = {
    allow: TOOL_IDS.filter((id) => allow.has(id)),
    deny: TOOL_IDS.filter((id) => deny.has(id)),
  }
  return next
}

const READ_RANK = { none: 0, workspace: 1, all: 2 }
const WRITE_RANK = { none: 0, workspace: 1, all: 2 }
const SHELL_RANK = { deny: 0, allowlist: 1, allow: 2 }
const APPROVAL_RANK = { 'ask-always': 0, 'ask-external': 1, never: 2 }
const MCP_RANK = { none: 0, explicit: 1, 'init-defaults': 2 }

function tighter(rank, left, right) {
  const a = rank[left]
  const b = rank[right]
  if (a == null) return right
  if (b == null) return left
  return a <= b ? left : right
}

function intersectPolicies(...layers) {
  const list = layers.filter(Boolean).map((row) => normalizePolicy(row))
  if (list.length === 0) return normalizePolicy({ preset: INIT_PRESET })
  return list.reduce((acc, row) => {
    const allow = TOOL_IDS.filter((id) => isToolEnabled(acc, id) && isToolEnabled(row, id))
    return {
      preset: acc.preset,
      enforced: true,
      files: {
        read: tighter(READ_RANK, acc.files.read, row.files.read),
        write: tighter(WRITE_RANK, acc.files.write, row.files.write),
      },
      shell: tighter(SHELL_RANK, acc.shell, row.shell),
      approval: tighter(APPROVAL_RANK, acc.approval, row.approval),
      mcp: tighter(MCP_RANK, acc.mcp, row.mcp),
      tools: {
        allow,
        deny: TOOL_IDS.filter((id) => allow.indexOf(id) < 0),
      },
      delegation: {
        maxDepth: Math.min(acc.delegation.maxDepth, row.delegation.maxDepth),
        roles: (acc.delegation.roles || []).filter((role) => (row.delegation.roles || []).includes(role)),
      },
      skills: {
        deny: [...new Set([
          ...((acc.skills && acc.skills.deny) || []),
          ...((row.skills && row.skills.deny) || []),
        ])],
      },
    }
  })
}

function officialPolicyFromPreset(name) {
  if (name === 'read-only') return applyPreset('research')
  if (name === 'workspace-write') return applyPreset('developer')
  return applyPreset('full')
}

function maxPolicy() {
  return applyPreset('full')
}

function clawHardCap() {
  return normalizePolicy({
    ...applyPreset('developer'),
    files: { read: 'all', write: 'all' },
    tools: { allow: TOOL_IDS.slice(), deny: [] },
  })
}

function clampPolicy(policy, ceiling) {
  return intersectPolicies(normalizePolicy(policy), normalizePolicy(ceiling))
}

function sealReadOnlyRuntime(policy) {
  const next = normalizePolicy(policy)
  if (!next.files || next.files.write !== 'none') return next
  if (next.files.read === 'all') return next
  const allow = (next.tools.allow || []).filter((id) => id !== 'bash')
  const deny = (next.tools.deny || []).slice()
  if (deny.indexOf('bash') < 0) deny.push('bash')
  return { ...next, shell: 'deny', tools: { allow, deny } }
}

function clampClawPolicy(policy) {
  return sealReadOnlyRuntime(clampPolicy(policy, clawHardCap()))
}

function officialSandboxOf(policy) {
  if (policy && policy.files && policy.files.write === 'all' && policy.shell === 'allow') {
    return 'danger-full-access'
  }
  if (policy && policy.files && policy.files.write !== 'none') return 'workspace-write'
  return 'read-only'
}

function officialApprovalOf(policy) {
  if (policy && policy.approval === 'never') return 'never'
  return 'ask'
}

function tighterSandbox(wanted, current) {
  const rank = { 'read-only': 0, 'workspace-write': 1, 'danger-full-access': 2 }
  if (!wanted) return current || null
  if (!current) return wanted
  return rank[wanted] <= rank[current] ? wanted : current
}

function optionAllowed(ceiling, face, value) {
  const trial = normalizePolicy({
    ...ceiling,
    ...(face === 'files.read' ? { files: { ...ceiling.files, read: value } } : {}),
    ...(face === 'files.write' ? { files: { ...ceiling.files, write: value } } : {}),
    ...(face === 'shell' ? { shell: value } : {}),
    ...(face === 'approval' ? { approval: value } : {}),
    ...(face === 'mcp' ? { mcp: value } : {}),
  })
  const clamped = intersectPolicies(trial, ceiling)
  if (face === 'files.read') return clamped.files.read === value
  if (face === 'files.write') return clamped.files.write === value
  if (face === 'shell') return clamped.shell === value
  if (face === 'approval') return clamped.approval === value
  if (face === 'mcp') return clamped.mcp === value
  return true
}

function asArgs(args) {
  if (typeof args === 'string') {
    try {
      const parsed = JSON.parse(args)
      return parsed && typeof parsed === 'object' ? parsed : {}
    } catch {
      return {}
    }
  }
  return args && typeof args === 'object' && !Array.isArray(args) ? args : {}
}

function commandOf(args) {
  const value = asArgs(args)
  return String(value.command || value.cmd || '').toLowerCase()
}

const OPENCLAW_FS = {
  read: 'read',
  glob: 'read',
  grep: 'read',
  read_file: 'read',
  read_image: 'read',
  write: 'write',
  create_file: 'write',
  edit: 'edit',
  apply_patch: 'apply_patch',
  bash: 'bash',
  exec: 'bash',
  shell: 'bash',
  deploy: 'deploy',
}

function workspaceAccessOf(policy, cls) {
  if (!policy || !policy.files) return 'none'
  if (cls === 'read') {
    if (policy.files.read === 'all') return 'all'
    if (policy.files.read === 'workspace') return 'ro'
    return 'none'
  }
  if (cls === 'write' || cls === 'edit' || cls === 'apply_patch') {
    if (policy.files.write === 'all') return 'all'
    if (policy.files.write === 'workspace') return 'rw'
    return 'none'
  }
  if (policy.files.read === 'all' || policy.files.write === 'all') return 'all'
  if (policy.files.write === 'workspace') return 'rw'
  if (policy.files.read === 'workspace') return 'ro'
  return 'none'
}

function classifyTool(name, args) {
  const id = String(name || '').toLowerCase()
  if (OPENCLAW_FS[id]) return OPENCLAW_FS[id]
  if (id === 'str_replace_editor') {
    const cmd = commandOf(args)
    if (cmd === 'view' || cmd === 'read') return 'read'
    if (cmd === 'create' || cmd === 'write') return 'write'
    return 'edit'
  }
  if (id.includes('mcp')) return 'other'
  if (id.includes('subagent') || id.includes('delegate')) return 'other'
  return 'other'
}

function allowTool(policy, name, args) {
  if (!policy) return false
  const id = String(name || '').toLowerCase()
  if (id === 'skill') return true
  if (id.includes('mcp') && policy.mcp === 'none') return false
  if ((id.includes('subagent') || id.includes('delegate')) && policy.delegation.maxDepth <= 0) {
    return false
  }
  const cls = classifyTool(name, args)
  if (cls === 'other') {
    return policy.files.write !== 'none' || policy.shell !== 'deny'
  }
  if (cls === 'edit' || cls === 'write' || cls === 'apply_patch') {
    if (cls === 'apply_patch') return isToolEnabled(policy, 'apply_patch') || isToolEnabled(policy, 'edit')
    return isToolEnabled(policy, cls)
  }
  return isToolEnabled(policy, cls)
}

const SESSION_ID_RE = /^session-[A-Za-z0-9-]{6,}$/

function isSessionId(value) {
  return typeof value === 'string' && SESSION_ID_RE.test(value)
}

const NS = 'dsh-session-permissions'

const COPY = {
  zh: {
    tab: '权限',
    title: '权限',
    intro: '',
    on: '启用',
    off: '停用',
    session: '会话',
    agent: '所属 Agent',
    official: '官方预设',
    ceiling: '天花板',
    effective: '有效权限',
    sourceInherit: '尚未单独保存：工作区默认最大，Claw 继承其天花板',
    sourceSession: '已保存为本会话覆盖（已按天花板收紧）',
    clamped: '已按天花板收紧，超限选项不可选。Claw 不能选无限制终端或官方最高权限。',
    template: '预设基类',
    filesRead: '文件读',
    filesWrite: '文件写',
    shell: '终端',
    approval: '审批',
    mcp: 'MCP',
    delegation: '委派深度',
    tools: '工具',
    tool_read: '读取',
    tool_write: '写入',
    tool_edit: '修改',
    tool_apply_patch: '应用补丁',
    tool_bash: '命令行',
    tool_deploy: '对外发布',
    toolhint_read: '打开并阅读文件内容。',
    toolhint_write: '新建文件，或把整个文件覆盖成新内容。',
    toolhint_edit: '在已有文件里改几处，不整份覆盖。',
    toolhint_apply_patch: '按一段 diff（补丁）一次改多处代码。',
    toolhint_bash: '在这台电脑上执行命令。',
    toolhint_deploy: '允许调用发布类工具，把构建结果推到仓库外或线上。官方默认不带这个工具；打开后，只有装了对应插件或技能才会真正执行。',
    read: '读取',
    write: '写入',
    edit: '修改',
    apply_patch: '应用补丁',
    bash: '命令行',
    deploy: '对外发布',
    save: '保存',
    saved: '已保存（未超过天花板）',
    reset: '恢复继承',
    fail: '操作失败',
    none: '无',
    workspace: '工作区',
    all: '全部',
    deny: '拒绝',
    allowlist: '白名单',
    allow: '允许',
    never: '不询问',
    askExternal: '外部才问',
    askAlways: '每次都问',
    mcpNone: '无',
    mcpExplicit: '仅显式',
    mcpInit: '初始化默认',
    full: '最大',
    research: '只读',
    developer: '开发',
    reviewer: '审阅',
    release: '发布',
    public: '公开',
    officialDanger: '完全访问',
    officialWrite: '工作区写入',
    officialRead: '只读',
    officialCustom: '自定义',
  },
  en: {
    tab: 'Permissions',
    title: 'Permissions',
    intro: '',
    on: 'On',
    off: 'Off',
    session: 'Session',
    agent: 'Agent',
    official: 'Official preset',
    ceiling: 'Ceiling',
    effective: 'Effective',
    sourceInherit: 'Not saved yet: workspace defaults to maximum; Claw inherits its ceiling',
    sourceSession: 'Saved as a session override (clamped to the ceiling)',
    clamped: 'Clamped to the ceiling. Claw cannot choose unrestricted shell, deploy, or danger-full-access.',
    template: 'Preset template',
    filesRead: 'File read',
    filesWrite: 'File write',
    shell: 'Shell',
    approval: 'Approval',
    mcp: 'MCP',
    delegation: 'Delegation depth',
    tools: 'Tools',
    save: 'Save',
    saved: 'Saved (within the ceiling)',
    reset: 'Inherit again',
    fail: 'Request failed',
    none: 'None',
    workspace: 'Workspace',
    all: 'Anywhere',
    deny: 'Deny',
    allowlist: 'Allowlist',
    allow: 'Allow',
    never: 'Never',
    askExternal: 'Ask if external',
    askAlways: 'Ask always',
    mcpNone: 'None',
    mcpExplicit: 'Explicit only',
    mcpInit: 'Init defaults',
    full: 'Maximum',
    research: 'Read only',
    developer: 'Developer',
    reviewer: 'Reviewer',
    release: 'Release',
    public: 'Public',
    tool_read: 'Read',
    tool_write: 'Write',
    tool_edit: 'Edit',
    tool_apply_patch: 'Apply patch',
    tool_bash: 'Command line',
    tool_deploy: 'Publish',
    toolhint_read: 'Open and read file contents.',
    toolhint_write: 'Create a file or overwrite it entirely.',
    toolhint_edit: 'Change parts of an existing file without replacing the whole file.',
    toolhint_apply_patch: 'Apply a diff to change several places at once.',
    toolhint_bash: 'Run commands on this computer.',
    toolhint_deploy: 'Allow publish/deploy tools that push a build outside the workspace. DSH does not ship this tool; turning it on only matters if a plugin or skill provides it.',
    read: 'Read',
    write: 'Write',
    edit: 'Edit',
    apply_patch: 'Apply patch',
    bash: 'Command line',
    deploy: 'Publish',
    officialDanger: 'Full access',
    officialWrite: 'Workspace Write',
    officialRead: 'Read Only',
    officialCustom: 'Custom',
  },
}

function interpolate(template, params) {
  if (params == null) return template
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (
    Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match
  ))
}

function activeLocaleId(ctx) {
  try {
    const locale = ctx && ctx.locale
    const snap = locale && (locale.getLocale ? locale.getLocale() : locale.getSnapshot && locale.getSnapshot())
    if (snap && typeof snap.active === 'string' && snap.active) return snap.active
  } catch { /* inject miss */ }
  const tag = (typeof document !== 'undefined' && document.documentElement && document.documentElement.lang) || 'zh'
  return tag
}

function isZh(ctx) {
  return String(activeLocaleId(ctx)).toLowerCase().indexOf('zh') === 0
}

function translate(lang, key, params) {
  const table = COPY[lang] || COPY.en
  return interpolate(table[key] ?? COPY.en[key] ?? key, params)
}

function tWith(ctx, key, params) {
  try {
    const locale = ctx && ctx.locale
    if (locale && typeof locale.bind === 'function') {
      const translated = locale.bind(NS)(key, params)
      if (translated && translated !== key) return interpolate(translated, params)
    }
  } catch { /* fall through */ }
  return translate(isZh(ctx) ? 'zh' : 'en', key, params)
}

const ATTR = 'data-dsh-session-permissions'

const CSS = [
  'body[' + ATTR + '] .dsp-page{display:flex;flex-direction:column;gap:18px;width:100%;max-width:720px;margin:0 auto;padding:8px 24px 36px;color:var(--dsw-alias-label-primary);box-sizing:border-box;overflow:visible}',
  'body[' + ATTR + '] .dsp-perm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px 20px;overflow:visible}',
  'body[' + ATTR + '] .dsp-perm-item{display:flex;flex-direction:column;gap:8px;min-width:0;overflow:visible}',
  'body[' + ATTR + '] .dsp-perm-item[data-span="2"]{grid-column:1/-1}',
  'body[' + ATTR + '] .dsp-perm-k{font-size:13px;line-height:20px;color:var(--dsw-alias-label-tertiary)}',
  'body[' + ATTR + '] .dsp-segs{display:flex;flex-wrap:wrap;gap:8px}',
  'body[' + ATTR + '] .dsp-seg{height:36px;padding:0 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:inherit;font:inherit;font-size:14px;line-height:20px;cursor:pointer}',
  'body[' + ATTR + '] .dsp-seg:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-seg[data-on="true"]{border-color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-seg:disabled{opacity:.4;cursor:not-allowed}',
  'body[' + ATTR + '] .dsp-cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;overflow:visible}',
  'body[' + ATTR + '] .dsp-tile{box-sizing:border-box;display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:58px;padding:14px 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-3,transparent);color:inherit;font:inherit;text-align:left;cursor:pointer;overflow:visible}',
  'body[' + ATTR + '] .dsp-tile:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-tile[disabled]{opacity:.4;cursor:not-allowed}',
  'body[' + ATTR + '] .dsp-tile-lead{display:flex;align-items:center;min-width:0;gap:2px}',
  'body[' + ATTR + '] .dsp-tile-title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:15px;line-height:22px;font-weight:600}',
  'body[' + ATTR + '] .dsp-hint{flex:none;position:relative;display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;margin-left:6px;border:1px solid currentColor;border-radius:50%;font-size:11px;font-weight:700;line-height:1;opacity:.5;cursor:help}',
  'body[' + ATTR + '] .dsp-hint:hover,body[' + ATTR + '] .dsp-hint:focus-visible{opacity:1}',
  'body[' + ATTR + '] .dsp-hint::after{content:attr(data-tip);position:absolute;left:50%;top:calc(100% + 8px);transform:translateX(-50%);width:max-content;max-width:240px;padding:8px 10px;border-radius:8px;background:var(--dsw-alias-bg-layer-3,#1b1e24);border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);font-size:12px;font-weight:400;line-height:18px;white-space:normal;box-shadow:var(--dsw-shadow-lv3,0 8px 24px rgba(0,0,0,.18));opacity:0;pointer-events:none;z-index:2147483002}',
  'body[' + ATTR + '] .dsp-hint:hover::after,body[' + ATTR + '] .dsp-hint:focus-visible::after{opacity:1}',
  'body[' + ATTR + '] .dsp-tag{flex:none;display:inline-flex;align-items:center;height:24px;padding:0 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;font-size:12px;color:var(--dsw-alias-label-tertiary)}',
  'body[' + ATTR + '] .dsp-tag[data-on="true"]{color:var(--dsw-alias-label-primary)}',
  'body[' + ATTR + '] .dsp-num{height:36px;width:80px;padding:0 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:inherit;font:inherit;font-size:14px}',
  'body[' + ATTR + '] .dsp-actions{display:flex;gap:10px;margin-top:4px}',
  'body[' + ATTR + '] .dsp-btn{height:36px;padding:0 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:inherit;cursor:pointer;font-size:14px}',
  'body[' + ATTR + '] .dsp-btn:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-btn:disabled{opacity:.45;cursor:not-allowed}',
  'body[' + ATTR + '] .dsp-toast{position:fixed;left:50%;bottom:28px;transform:translateX(-50%);z-index:2147483001;padding:8px 14px;border-radius:10px;background:var(--dsw-alias-bg-layer-3,#1b1e24);border:1px solid var(--dsw-alias-border-l2);font-size:13px}',
  '@media (max-width:640px){body[' + ATTR + '] .dsp-perm-grid,body[' + ATTR + '] .dsp-cards{grid-template-columns:1fr}}',
  '@media (prefers-reduced-motion:reduce){body[' + ATTR + '] *{transition:none}}',
].join('\n')

const PRESET_LABEL = {
  full: 'full',
  research: 'research',
  developer: 'developer',
  reviewer: 'reviewer',
  release: 'release',
  public: 'public',
}

function createPermissionPage(React, t, post, toast, subscribeLocale) {
  return function PermissionPage(props) {
    const el = React.createElement
    const [, setLocaleTick] = React.useState(0)
    React.useEffect(() => {
      if (typeof subscribeLocale !== 'function') return undefined
      return subscribeLocale(() => setLocaleTick((n) => n + 1))
    }, [subscribeLocale])
    const sessionId = props && props.sessionId
    const cwd = props && props.useSessions
      ? props.useSessions((s) => (s.byId && sessionId && s.byId[sessionId] && s.byId[sessionId].cwd) || '')
      : ''
    const [ceiling, setCeiling] = React.useState(null)
    const [claw, setClaw] = React.useState(false)
    const [policy, setPolicy] = React.useState(null)
    const [busy, setBusy] = React.useState(false)

    const applyLayers = React.useCallback((data) => {
      setCeiling(data.ceiling || null)
      setClaw(!!data.claw || !!(data.agent && data.agent.agentId))
      const next = data.session || data.effective
      setPolicy(next ? normalizePolicy(next) : null)
    }, [])

    const load = React.useCallback(() => {
      if (!sessionId) return Promise.resolve()
      return post('/dsh-session-permissions/read', { sessionId, cwd }).then((data) => {
        applyLayers(data)
      }).catch((err) => toast(String(err.message || t('fail'))))
    }, [sessionId, cwd, applyLayers])

    React.useEffect(() => { load() }, [load])

    function setClamped(next) {
      setPolicy(ceiling ? clampPolicy(next, ceiling) : normalizePolicy(next))
    }

    function save() {
      if (!sessionId || !policy) return
      setBusy(true)
      post('/dsh-session-permissions/write', { sessionId, cwd, policy }).then((data) => {
        applyLayers(data)
        toast(t('saved'))
      }).catch((err) => toast(String(err.message || t('fail')))).finally(() => setBusy(false))
    }

    function reset() {
      if (!sessionId) return
      setBusy(true)
      post('/dsh-session-permissions/reset', { sessionId, cwd }).then((data) => {
        applyLayers(data)
      }).catch((err) => toast(String(err.message || t('fail')))).finally(() => setBusy(false))
    }

    function field(label, control, span) {
      return el('div', { className: 'dsp-perm-item', 'data-span': span ? '2' : undefined },
        el('div', { className: 'dsp-perm-k' }, label),
        control,
      )
    }

    function segs(value, options, onChange) {
      return el('div', { className: 'dsp-segs' }, options.map((opt) => el('button', {
        key: opt.id,
        type: 'button',
        className: 'dsp-seg',
        'data-on': value === opt.id ? 'true' : undefined,
        disabled: !!opt.disabled,
        onClick() { if (!opt.disabled) onChange(opt.id) },
      }, opt.label)))
    }

    function faceOptions(face, ids, labels) {
      return ids.map((id) => ({
        id,
        label: labels[id],
        disabled: ceiling ? !optionAllowed(ceiling, face, id) : false,
      }))
    }

    if (!policy) {
      return el('div', { className: 'dsp-page' })
    }

    return el('div', { className: 'dsp-page' },
      el('div', { className: 'dsp-perm-grid' },
        field(t('template'), segs(policy.preset, (claw ? PRESET_IDS.filter((id) => id !== 'full') : PRESET_IDS).map((id) => ({ id, label: t(PRESET_LABEL[id]) })), (id) => {
          setClamped(applyPreset(id))
        }), true),
        field(t('filesRead'), segs(policy.files.read, faceOptions('files.read', ['none', 'workspace', 'all'], {
          none: t('none'),
          workspace: t('workspace'),
          all: t('all'),
        }), (id) => setClamped({ ...policy, files: { ...policy.files, read: id } }))),
        field(t('filesWrite'), segs(policy.files.write, faceOptions('files.write', ['none', 'workspace', 'all'], {
          none: t('none'),
          workspace: t('workspace'),
          all: t('all'),
        }), (id) => setClamped({ ...policy, files: { ...policy.files, write: id } }))),
        field(t('shell'), segs(policy.shell, faceOptions('shell', ['deny', 'allowlist', 'allow'], {
          deny: t('deny'),
          allowlist: t('allowlist'),
          allow: t('allow'),
        }), (id) => setClamped({ ...policy, shell: id }))),
        field(t('approval'), segs(policy.approval, faceOptions('approval', ['never', 'ask-external', 'ask-always'], {
          never: t('never'),
          'ask-external': t('askExternal'),
          'ask-always': t('askAlways'),
        }), (id) => setClamped({ ...policy, approval: id }))),
        field(t('mcp'), segs(policy.mcp, faceOptions('mcp', ['none', 'explicit', 'init-defaults'], {
          none: t('mcpNone'),
          explicit: t('mcpExplicit'),
          'init-defaults': t('mcpInit'),
        }), (id) => setClamped({ ...policy, mcp: id }))),
        field(t('delegation'), el('input', {
          className: 'dsp-num',
          type: 'number',
          min: 0,
          max: ceiling ? ceiling.delegation.maxDepth : 8,
          value: policy.delegation.maxDepth,
          onChange(e) {
            setClamped({ ...policy, delegation: { maxDepth: e.target.value } })
          },
        })),
        field(t('tools'), el('div', { className: 'dsp-cards' }, TOOL_IDS.map((id) => {
          const locked = ceiling ? !isToolEnabled(ceiling, id) : false
          const on = isToolEnabled(policy, id)
          return el('button', {
            key: id,
            type: 'button',
            className: 'dsp-tile',
            disabled: locked,
            onClick() {
              if (locked) return
              setClamped(toggleTool(policy, id, !on))
            },
          },
            el('span', { className: 'dsp-tile-lead' },
              el('span', { className: 'dsp-tile-title' }, t('tool_' + id)),
              el('span', {
                className: 'dsp-hint',
                tabIndex: 0,
                'data-tip': t('toolhint_' + id),
                'aria-label': t('toolhint_' + id),
                onClick(e) { e.preventDefault(); e.stopPropagation() },
                onKeyDown(e) { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); e.stopPropagation() } },
              }, '!'),
            ),
            el('span', { className: 'dsp-tag', 'data-on': on ? 'true' : 'false' }, on ? t('on') : t('off')),
          )
        })), true),
      ),
      el('div', { className: 'dsp-actions' },
        el('button', { type: 'button', className: 'dsp-btn', disabled: busy, onClick: save }, t('save')),
        el('button', { type: 'button', className: 'dsp-btn', disabled: busy, onClick: reset }, t('reset')),
      ),
    )
  }
}

function apply(ctx) {
  const React = require('react')
  const slots = ctx.get('slots')
  if (slots == null || React == null) return

  const doc = typeof document === 'undefined' ? null : document
  let styleTag = null
  if (doc && doc.head) {
    styleTag = doc.createElement('style')
    styleTag.setAttribute(ATTR, '')
    styleTag.textContent = CSS
    doc.head.appendChild(styleTag)
    doc.body.setAttribute(ATTR, '')
  }

  let localeDispose = function () {}
  try {
    if (ctx.locale && typeof ctx.locale.register === 'function') {
      localeDispose = ctx.locale.register(NS, COPY) || function () {}
    }
  } catch { /* remount */ }

  function t(key, params) {
    return interpolate(tWith(ctx, key, params), params)
  }

  function subscribeLocale(fn) {
    if (ctx.locale && typeof ctx.locale.subscribe === 'function') {
      return ctx.locale.subscribe(fn) || function () {}
    }
    return function () {}
  }

  function post(path, payload) {
    return fetch(path, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-DSH-Session-Permissions': '1' },
      body: JSON.stringify(payload || {}),
    }).then((res) => res.json().then((data) => {
      if (!res.ok && (!data || data.ok !== true)) throw new Error((data && data.error) || ('http ' + res.status))
      return data
    }))
  }

  function toast(message) {
    if (!doc) return
    const existing = doc.querySelector('.dsp-toast')
    if (existing) existing.remove()
    const el = document.createElement('div')
    el.className = 'dsp-toast'
    el.textContent = message
    doc.body.appendChild(el)
    setTimeout(() => { if (el.parentNode) el.remove() }, 1800)
  }

  const Page = createPermissionPage(React, t, post, toast, subscribeLocale)
  const stopView = slots.inject('conversation.view', function () {
    return slots.register({
      name: 'conversation.view',
      id: 'session-permissions',
      order: 40,
      locale: NS,
      label() { return t('tab') },
    }, Page)
  })

  ctx.effect(() => {
    return function () {
      localeDispose()
      if (typeof stopView === 'function') stopView()
      if (styleTag != null) styleTag.remove()
      if (doc) doc.body.removeAttribute(ATTR)
    }
  })
}


    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
