import {
  APPROVAL_IDS,
  INIT_PRESET,
  MCP_IDS,
  POLICY_SCHEMA_VERSION,
  PRESET_IDS,
  READ_IDS,
  SHELL_IDS,
  TOOL_IDS,
  WRITE_IDS,
  allowTool,
  applyPreset,
  asArgs,
  clampClawPolicy,
  clampPolicy,
  classifyTool,
  clawHardCap,
  declaredOf,
  intersectPolicies,
  isPresetId,
  isToolEnabled,
  maxPolicy,
  normalizePolicy,
  officialApprovalOf,
  officialPolicyFromPreset,
  officialSandboxOf,
  optionAllowed,
  tighterSandbox,
  toggleTool,
  workspaceAccessOf,
} from '../dsh-agent-policy/policy-schema.mjs'

export {
  APPROVAL_IDS,
  INIT_PRESET,
  MCP_IDS,
  POLICY_SCHEMA_VERSION,
  PRESET_IDS,
  READ_IDS,
  SHELL_IDS,
  TOOL_IDS,
  WRITE_IDS,
  allowTool,
  applyPreset,
  asArgs,
  clampClawPolicy,
  clampPolicy,
  classifyTool,
  clawHardCap,
  declaredOf,
  intersectPolicies,
  isPresetId,
  isToolEnabled,
  maxPolicy,
  normalizePolicy,
  officialApprovalOf,
  officialPolicyFromPreset,
  officialSandboxOf,
  optionAllowed,
  tighterSandbox,
  toggleTool,
  workspaceAccessOf,
}

export const SESSION_ID_RE = /^session-[A-Za-z0-9-]{6,}$/

export function isSessionId(value) {
  return typeof value === 'string' && SESSION_ID_RE.test(value)
}
