export const ATTR = 'data-dsh-session-permissions'

export const CSS = [
  'body[' + ATTR + '] .dsp-page{display:flex;flex-direction:column;gap:18px;width:100%;max-width:720px;margin:0 auto;padding:8px 24px 36px;color:var(--dsw-alias-label-primary);box-sizing:border-box;overflow:visible}',
  'body[' + ATTR + '] .dsp-perm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px 20px;overflow:visible}',
  'body[' + ATTR + '] .dsp-perm-item{display:flex;flex-direction:column;gap:8px;min-width:0;overflow:visible}',
  'body[' + ATTR + '] .dsp-perm-item[data-span="2"]{grid-column:1/-1}',
  'body[' + ATTR + '] .dsp-perm-k{font-size:13px;line-height:20px;color:var(--dsw-alias-label-tertiary)}',
  'body[' + ATTR + '] .dsp-segs{display:flex;flex-wrap:wrap;gap:8px}',
  'body[' + ATTR + '] .dsp-seg{height:36px;padding:0 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:inherit;font:inherit;font-size:14px;line-height:20px;cursor:pointer}',
  'body[' + ATTR + '] .dsp-seg:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-seg[data-on="true"]{border-color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-seg:disabled{opacity:.4;cursor:not-allowed}',
  'body[' + ATTR + '] .dsp-cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;overflow:visible}',
  'body[' + ATTR + '] .dsp-tile{box-sizing:border-box;display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:58px;padding:14px 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-3,transparent);color:inherit;font:inherit;text-align:left;cursor:pointer;overflow:visible}',
  'body[' + ATTR + '] .dsp-tile:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-tile[disabled]{opacity:.4;cursor:not-allowed}',
  'body[' + ATTR + '] .dsp-tile-lead{display:flex;align-items:center;min-width:0;gap:2px}',
  'body[' + ATTR + '] .dsp-tile-title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:15px;line-height:22px;font-weight:600}',
  'body[' + ATTR + '] .dsp-hint{flex:none;position:relative;display:inline-flex;align-items:center;justify-content:center;width:16px;height:16px;margin-left:6px;border:1px solid currentColor;border-radius:50%;font-size:11px;font-weight:700;line-height:1;opacity:.5;cursor:help}',
  'body[' + ATTR + '] .dsp-hint:hover,body[' + ATTR + '] .dsp-hint:focus-visible{opacity:1}',
  'body[' + ATTR + '] .dsp-hint::after{content:attr(data-tip);position:absolute;left:50%;top:calc(100% + 8px);transform:translateX(-50%);width:max-content;max-width:240px;padding:8px 10px;border-radius:8px;background:var(--dsw-alias-bg-layer-3,#1b1e24);border:1px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-primary);font-size:12px;font-weight:400;line-height:18px;white-space:normal;box-shadow:var(--dsw-shadow-lv3,0 8px 24px rgba(0,0,0,.18));opacity:0;pointer-events:none;z-index:2147483002}',
  'body[' + ATTR + '] .dsp-hint:hover::after,body[' + ATTR + '] .dsp-hint:focus-visible::after{opacity:1}',
  'body[' + ATTR + '] .dsp-tag{flex:none;display:inline-flex;align-items:center;height:24px;padding:0 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;font-size:12px;color:var(--dsw-alias-label-tertiary)}',
  'body[' + ATTR + '] .dsp-tag[data-on="true"]{color:var(--dsw-alias-label-primary)}',
  'body[' + ATTR + '] .dsp-num{height:36px;width:80px;padding:0 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:inherit;font:inherit;font-size:14px}',
  'body[' + ATTR + '] .dsp-actions{display:flex;gap:10px;margin-top:4px}',
  'body[' + ATTR + '] .dsp-btn{height:36px;padding:0 16px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:transparent;color:inherit;cursor:pointer;font-size:14px}',
  'body[' + ATTR + '] .dsp-btn:hover{background:var(--dsw-alias-interactive-bg-hover)}',
  'body[' + ATTR + '] .dsp-btn:disabled{opacity:.45;cursor:not-allowed}',
  'body[' + ATTR + '] .dsp-toast{position:fixed;left:50%;bottom:28px;transform:translateX(-50%);z-index:2147483001;padding:8px 14px;border-radius:10px;background:var(--dsw-alias-bg-layer-3,#1b1e24);border:1px solid var(--dsw-alias-border-l2);font-size:13px}',
  '@media (max-width:640px){body[' + ATTR + '] .dsp-perm-grid,body[' + ATTR + '] .dsp-cards{grid-template-columns:1fr}}',
  '@media (prefers-reduced-motion:reduce){body[' + ATTR + '] *{transition:none}}',
].join('\n')
