import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const policySchema = join(root, '..', 'dsh-agent-policy', 'policy-schema.mjs')

function stripModule(src) {
  return src
    .replace(/^import[\s\S]*?from '[^']+'\n+/gm, '')
    .replace(/^export \{[\s\S]*?\}\s*(from '[^']+')?\n+/gm, '')
    .replace(/^export /gm, '')
}

const parts = [
  stripModule(readFileSync(policySchema, 'utf8')),
  ...[
    'perm-schema.mjs',
    'perm-i18n.mjs',
    'perm-styles.mjs',
    'perm-page.mjs',
    'perm-runtime.mjs',
  ].map((file) => stripModule(readFileSync(join(root, file), 'utf8'))),
]

const banner = `// Generated by scripts/build-client.mjs. Do not edit by hand.

`
const body = `window.__ModuleLoader__.load({
  id: 'dsh-session-permissions',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    var name = 'dsh-session-permissions'
    var inject = ['slots', 'locale']

${parts.join('\n')}

    exports.name = name
    exports.inject = inject
    exports.apply = apply
    return module.exports
  },
})
`

const next = banner + body
const dest = join(root, 'client.js')
const check = process.argv.includes('--check')
if (check) {
  const current = readFileSync(dest, 'utf8')
  if (current !== next) {
    console.error('client.js is stale; run node scripts/build-client.mjs')
    process.exit(1)
  }
  process.exit(0)
}
writeFileSync(dest, next)
